### ISSUE TITLE
How can you pass objects into the sandbox?

### ISSUE THREAD

**Issue by Zentendo** [fulcrumapp/v8-sandbox#1]
How can you pass objects to be used in the sandbox? Such as variables, functions, ect.

**Comment by zhm** [comment]
It's intentionally not possible to pass objects directly to the sandbox. But you can expose functions to the sandbox and it will use JSON serialization to pass the result back.

Here is an example:

https://github.com/fulcrumapp/v8-sandbox/blob/master/example-functions.js
