### ISSUE TITLE
Limit execution time

### ISSUE THREAD

**Issue by merlinfuchs** [fulcrumapp/v8-sandbox#10]
As far as I can tell, the timeout doesn't actually kill the running script, correct?
It would be great if there was a way to kill a script after time X or even limit the CPU-time.

**Comment by CyberPhoenix90** [comment]
You can use sandbox.shutdown() to achieve the desired effect.

**Comment by zhm** [comment]
I'm very late commenting on this, but replying anyways in case anyone else finds it useful.

Here is an example in the tests of using the `timeout` property. https://github.com/fulcrumapp/v8-sandbox/blob/46e192b983ea45e6ac83f5ca2607bf9efc046f53/test/index.js#L379-L393

Also, `shutdown()` is required to clean up the sandbox or else the node process will never exit. Once a sandbox is created it must be destroyed with `shutdown()` explicitly.
