### ISSUE TITLE
node-pre-gyp ERR! build error

### ISSUE THREAD

**Issue by WildXBird** [fulcrumapp/v8-sandbox#17]
I encountered an error when installing it on Windows, what should I do?
I tried to delete node_modules and reinstall it, but the same error was displayed.

...
703 timing build:link:node_modules/rimraf Completed in 14ms
704 timing build:link:node_modules/uuid Completed in 13ms
705 timing build:link:node_modules/sshpk Completed in 14ms
706 timing build:link:node_modules/which Completed in 13ms
707 timing build:link Completed in 15ms
708 info run v8-sandbox@2.2.2 install node_modules/v8-sandbox node-gyp rebuild
709 info run v8-sandbox@2.2.2 install { code: 1, signal: null }
710 timing reify:rollback:createSparse Completed in 189ms
711 timing reify:rollback:retireShallow Completed in 0ms
712 timing command:install Completed in 9319ms
713 verbose stack Error: command failed
713 verbose stack     at ChildProcess.<anonymous> (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
713 verbose stack     at ChildProcess.emit (events.js:315:20)
713 verbose stack     at maybeClose (internal/child_process.js:1048:16)
713 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
714 verbose pkgid v8-sandbox@2.2.2
715 verbose cwd D:\Github\JSVMachine\vm\g3
716 verbose Windows_NT 10.0.17763
717 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\John\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "v8-sandbox" "--save"
718 verbose node v14.16.0
719 verbose npm  v7.9.0
720 error code 1
721 error path D:\Github\JSVMachine\vm\node_modules\v8-sandbox
722 error command failed
723 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
724 error ?????????????????????????????????????????????????????????????????????
724 error   addon.cc
724 error   baton.cc
724 error   sandbox.cc
724 error   win_delay_load_hook.cc
724 error ..\src\sandbox.cc(398): error C2059: syntax error: '.' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(398): error C2143: syntax error: missing ';' before '}' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(399): error C2059: syntax error: '}' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(399): error C2143: syntax error: missing ';' before '}' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(401): error C3927: '->': trailing return type is not allowed after a non-function declarator [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(401): error C3613: missing return type after '->' ('int' assumed) [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(401): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(401): error C2146: syntax error: missing ';' before identifier 'data' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(403): error C2065: 'pipe': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(403): error C2065: 'buffers': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(403): error C2065: 'OnWriteComplete': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(403): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(403): error C2365: 'uv_write': redefinition; previous definition was 'function' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error   C:\Users\John\AppData\Local\node-gyp\Cache\14.16.0\include\node\uv.h(509): note: see declaration of 'uv_write'
724 error ..\src\sandbox.cc(405): error C2065: 'pipe': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(405): error C2065: 'AllocateBuffer': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(405): error C2065: 'OnRead': undeclared identifier [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(405): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(405): error C2365: 'uv_read_start': redefinition; previous definition was 'function' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error   C:\Users\John\AppData\Local\node-gyp\Cache\14.16.0\include\node\uv.h(504): note: see declaration of 'uv_read_start'
724 error ..\src\sandbox.cc(406): error C2059: syntax error: '}' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(406): error C2143: syntax error: missing ';' before '}' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(408): error C2143: syntax error: missing ';' before '{' [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
724 error ..\src\sandbox.cc(408): error C2447: '{': missing function header (old-style formal list?) [D:\Github\JSVMachine\vm\node_modules\v8-sandbox\build\sandbox.vcxproj]
725 error gyp info it worked if it ends with ok
725 error gyp info using node-gyp@6.1.0
725 error gyp info using node@14.16.0 | win32 | x64
725 error gyp info find Python using Python version 2.7.15 found at "C:\Users\John\.windows-build-tools\python27\python.exe"
725 error gyp info find VS using VS2015 (14.0) found at:
725 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
725 error gyp info find VS run with --verbose for detailed information
725 error gyp info spawn C:\Users\John\.windows-build-tools\python27\python.exe
725 error gyp info spawn args [
725 error gyp info spawn args   'D:\\Github\\JSVMachine\\vm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
725 error gyp info spawn args   'binding.gyp',
725 error gyp info spawn args   '-f',
725 error gyp info spawn args   'msvs',
725 error gyp info spawn args   '-I',
725 error gyp info spawn args   'D:\\Github\\JSVMachine\\vm\\node_modules\\v8-sandbox\\build\\config.gypi',
725 error gyp info spawn args   '-I',
725 error gyp info spawn args   'D:\\Github\\JSVMachine\\vm\\node_modules\\node-gyp\\addon.gypi',
725 error gyp info spawn args   '-I',
725 error gyp info spawn args   'C:\\Users\\John\\AppData\\Local\\node-gyp\\Cache\\14.16.0\\include\\node\\common.gypi',
725 error gyp info spawn args   '-Dlibrary=shared_library',
725 error gyp info spawn args   '-Dvisibility=default',
725 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\John\\AppData\\Local\\node-gyp\\Cache\\14.16.0',
725 error gyp info spawn args   '-Dnode_gyp_dir=D:\\Github\\JSVMachine\\vm\\node_modules\\node-gyp',
725 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\John\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.0\\\\<(target_arch)\\\\node.lib',
725 error gyp info spawn args   '-Dmodule_root_dir=D:\\Github\\JSVMachine\\vm\\node_modules\\v8-sandbox',
725 error gyp info spawn args   '-Dnode_engine=v8',
725 error gyp info spawn args   '--depth=.',
725 error gyp info spawn args   '--no-parallel',
725 error gyp info spawn args   '--generator-output',
725 error gyp info spawn args   'D:\\Github\\JSVMachine\\vm\\node_modules\\v8-sandbox\\build',
725 error gyp info spawn args   '-Goutput_dir=.'
725 error gyp info spawn args ]
725 error gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
725 error gyp info spawn args [
725 error gyp info spawn args   'build/binding.sln',
725 error gyp info spawn args   '/clp:Verbosity=minimal',
725 error gyp info spawn args   '/nologo',
725 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
725 error gyp info spawn args ]
725 error gyp ERR! build error
725 error gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
725 error gyp ERR! stack     at ChildProcess.onExit (D:\Github\JSVMachine\vm\node_modules\node-gyp\lib\build.js:194:23)
725 error gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
725 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
725 error gyp ERR! System Windows_NT 10.0.17763
725 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Github\\JSVMachine\\vm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
725 error gyp ERR! cwd D:\Github\JSVMachine\vm\node_modules\v8-sandbox
725 error gyp ERR! node -v v14.16.0
725 error gyp ERR! node-gyp -v v6.1.0
725 error gyp ERR! not ok
726 verbose exit 1

**Comment by antoine-cherfane** [comment]
If you are on windows, you need to have C/C++ compiler and Python installed. You can do that manually or simply install `windows-build-tools` globally using npm.

Some of the new versions of this package tend to get stuck during installation so I recommend you running the following command:

`npm install -g windows-build-tools@4.0.0`
