### ISSUE TITLE
Can't handle promise with .then()

### ISSUE THREAD

**Issue by songsanli** [fulcrumapp/v8-sandbox#2]
I'm playing v8-sandbox with below js code:

```javascript
const { default: Sandbox } = require("v8-sandbox");

const sandbox = new Sandbox();
const code = `
new Promise(resolve => {
  setTimeout(() => {
    resolve();
  }, 2000);
}).then(() => {
  while (true) {}
  setResult({value: 1});
})
`;

const result = await sandbox.execute({code, timeout: 10000});
console.log(result);
sandbox.shutdown();
```

It seems that `sandbox.execute()` will return the result (`{error: {}, output: []}`) after 2000ms, which means that code inside `.then()` is ignored.

Is this a feature or a bug?

**Comment by zhm** [comment]
Thank you for taking the time to report this bug. I fixed it in `0.4.3` and it's published on npm. Apologies for the delayed response.
